### ISSUE TITLE
Wrong error condition in SHAP kernel

### ISSUE THREAD

**Issue by memoryz** [bjlkeng/bjlkeng.github.io#4]
> When `|z'|=1` or `|z'|=M` the expression has a divide by zero

Should be: `|z'|=0` or `|z'|=M`

See: https://arxiv.org/pdf/1705.07874v1.pdf, second last paragraph on page 5.

**Comment by bjlkeng** [comment]
You are absolutely right, thanks so much for the correction!  I updated the post with the correction (and some other minor fixes): https://bjlkeng.github.io/posts/model-explanability-with-shapley-additive-explanations-shap/
