### ISSUE TITLE
How to treat divide by zero in SHAP kernel?

### ISSUE THREAD

**Issue by memoryz** [bjlkeng/bjlkeng.github.io#5]
In your [SHAP post ](https://bjlkeng.github.io/posts/model-explanability-with-shapley-additive-explanations-shap/), you mentioned:
> When |z′|=0 or |z′|=M the expression has a divide by zero, but you can just drop these terms in general (that's how I interpret what the paper says anyways).

I don't think you should drop these terms in general.

- When |z'| = 0, we know nothing about the data point to be explained. The predicted value equals the mean prediction of the model. The weighted linear model should then enforce this constraint by giving it a very big weight, so that the base value (intercept of the WLS model) would approximately [equal the mean prediction of the model](https://github.com/slundberg/shap/issues/352).

- When |z'| = M, every feature of the data point is present, and the coefficients and the intercept would sum up to the model output of the data point. The weighted linear model should also enforce this constraint by giving it a very big weight, so that the SHAP values (coefficients + intercept) would sum up to the predicted outcome of the data point. That essentially is the [Efficiency property from the Shapley values](https://en.wikipedia.org/wiki/Shapley_value#Efficiency).

So instead of dropping these terms, we should assign a big weight to them (something like 1E8). Note that for all other cases (|z'| between 1 and M-1), the SHAP kernel is guaranteed to be less than 1.

Finally, I really appreciate your great post! It helped me understand SHAP immensely.

**Comment by memoryz** [comment]
Nevermind... I realized it doesn't really matter. Practically these two cases are always skipped.

**Comment by bjlkeng** [comment]
Glad you found it useful!  Yeah, it's not so clear on what to do in those cases, but really it doesn't matter too much in the end I believe.
