### ISSUE TITLE
What is the LICENSE of this repository?

### ISSUE THREAD

**Issue by cia-rana** [bjlkeng/bjlkeng.github.io#6]
I'll write my article in Japanese based on your articles in this repository, but they are not licensed, so I would like to know about them.

**Comment by bjlkeng** [comment]
Hi @cia-rana, if you are just using my blog as a reference for your articles, I don't think there is a need to worry about licenses.  If you're going to copy and paste large portions of my posts, then we can discuss how you are going to use them.  In most cases, I'd be okay with it if you gave me clear attribution.  Feel free to reach out me, my email is here: https://briankeng.com/about/

I don't plan to explicitly add an open source license to my blog posts.
